export const MOVIES_LIST_FETCH_INIT = 'MOVIES_LIST_FETCH_INIT';
export const MOVIES_LIST_FETCH_SUCCESS = 'MOVIES_LIST_FETCH_SUCCESS';
export const MOVIES_LIST_FETCH_ERROR = 'MOVIES_LIST_FETCH_ERROR';
export const MOVIES_LIST_RESET = 'MOVIES_LIST_RESET';

export const GENRES_LIST_FETCH_INIT = 'GENRES_LIST_FETCH_INIT';
export const GENRES_LIST_FETCH_SUCCESS = 'GENRES_LIST_FETCH_SUCCESS';
export const GENRES_LIST_FETCH_ERROR = 'GENRES_LIST_FETCH_ERROR';

export const GENRES_SELECTION_UPDATE = 'GENRES_SELECTION_UPDATE';
